### ISSUE TITLE
Display "Meeting Spaces" Information

### ISSUE THREAD

**Issue by markmals** [APL-Innovation-Lab/meeting-room-prototype#21]
### Description

As a visitor to the Austin Public Library website,
I want to view detailed information about available meeting spaces,
So that I can easily understand the options and make reservations as needed.

#### Scenario: Viewing the Landing Page

- Given I am a visitor to the Austin Public Library website
- When I navigate to the "Meeting Spaces" landing page
- Then I can see a header image of the library's meeting spaces
- And I can see a prominent title "Meeting Spaces" and a descriptive paragraph outlining the benefits of using library meeting rooms

#### Scenario: Selecting a Reservation Option

- Given I am a visitor to the Austin Public Library website who has decided to look for a meeting room reservation
- When I navigate to the "Meeting Spaces" landing page
- Then I should be able to choose between a room for non-profit/non-commercial activity and a room for business/company work
- And when I select a room for non-profit/non-commercial activity, I should be taken to the "Find a Room" page for non-profit/non-commercial activity rooms
- And when I select a room for business/company work, I should be taken to the "Find a Room" page for a room for business/company work

#### Scenario: Viewing In-Person Reservation Details

- Given I am a visitor to the Austin Public Library website
- When I navigate to the "Meeting Spaces" landing page
- Then I should find additional details about how to reserve a room in-person

### Attachments
- [Link to design mockup](https://www.figma.com/design/DMjN6uhMLOw7VZO3t4eqjd/APL-Meeting-Room?node-id=637-26702&t=DwOq0IVK21777Av9-4)

### Implementation details
1. Take the elements that are already in APL (headers, services, menu etc)
2. Subdivide
3. Title, paragraph under title, "reserve online select" box, "reserve in person instead" info, and PDF link

**Comment by greenteaisgreat** [comment]
Changes Made:

- Add Header image
- Add Breadcrumb components
- Add 'Reserve Online' Select Component with Options
- Add 'Reserve In-Person' Section
- General Styling for Responsive Layout on All Components

Blockers: 
- Assets for .svg icons library still needed for USWDS components

**Comment by julielaursen** [comment]
Need to match the acceptance criteria with proposed A here: https://www.figma.com/design/DMjN6uhMLOw7VZO3t4eqjd/APL-Meeting-Room?node-id=1881-22526&t=r06Ia6RXth770WDw-0
